ARG release=18.04

FROM ubuntu:$release

ARG version=6.0
ARG triple=unknown-unknown-unknown
ARG threads=4

ENV DEBIAN_FRONTEND noninteractive

COPY . /llvm

RUN apt-get update -qq && \
    apt-get install -qq build-essential git python3 curl cmake && \
    cd /llvm && \
    ./build.sh
