name: CI
on: [push]

jobs:
  build:
    name: Build (os=${{ matrix.os }}, llvm=${{ matrix.llvm }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-12', 'windows-2022']
        llvm: ['18.1.7']
    steps:
      - uses: actions/checkout@v3
      - run: ./main.sh
        shell: bash
        env:
          version: ${{ matrix.llvm }}
          threads: 2
      - uses: actions/upload-artifact@v3
        with:
          name: clang+llvm-${{ matrix.llvm }}-${{ matrix.os }}
          path: clang+llvm-${{ matrix.llvm }}-*.*
